# Generated by Django 4.2.5 on 2024-10-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('publised', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
