# Generated by Django 4.2.5 on 2024-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_model',
            name='keyword',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
